name: CI/CD Kittygram

on:
  push:
    branches: [ main ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: 3.11

      - name: Install ruff and lint
        run: |
          pip install ruff
          ruff check backend/

      - name: Run Django tests
        run: |
          pip install -r backend/requirements.txt
          python backend/manage.py test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: node-version: 18

      - name: Install & test frontend
        run: |
          cd frontend
          npm ci
          npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ env.DOCKERHUB_USER }}/kittygram_backend:latest -f backend/Dockerfile .
          docker push ${{ env.DOCKERHUB_USER }}/kittygram_backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.DOCKERHUB_USER }}/kittygram_frontend:latest -f frontend/Dockerfile .
          docker push ${{ env.DOCKERHUB_USER }}/kittygram_frontend:latest

      - name: Build and push gateway image
        run: |
          docker build -t ${{ env.DOCKERHUB_USER }}/kittygram_gateway:latest -f nginx/Dockerfile .
          docker push ${{ env.DOCKERHUB_USER }}/kittygram_gateway:latest

      - name: Send Telegram notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
            -d text="✅ CI/CD Kittygram: весь pipeline успешно завершён" 

